import { execFileSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { describe, expect, it } from 'vitest';
import {
  formatTypeScriptProjectCoverageFailures,
  isTypeScriptSourcePath,
  runTypeScriptProjectCoverage,
  type DeclarationExclusion,
} from '../../../scripts/check-typescript-project-coverage.mts';

function createTrackedFixture(files: Readonly<Record<string, string>>): string {
  const root = mkdtempSync(join(tmpdir(), 'musixquare-ts-project-coverage-'));
  for (const [path, source] of Object.entries(files)) {
    const absolutePath = join(root, path);
    mkdirSync(dirname(absolutePath), { recursive: true });
    writeFileSync(absolutePath, source);
  }
  execFileSync('git', ['init', '--quiet'], { cwd: root, stdio: 'ignore' });
  execFileSync('git', ['add', '--all'], { cwd: root, stdio: 'ignore' });
  return root;
}

const FIXTURE_TSCONFIG = `${JSON.stringify(
  {
    compilerOptions: { noEmit: true, strict: true },
    include: ['src/**/*.ts'],
  },
  null,
  2,
)}\n`;

describe('TypeScript project coverage guard', () => {
  it('recognizes every authored TypeScript extension, including declaration files', () => {
    for (const path of [
      'src/app.ts',
      'src/view.tsx',
      'scripts/check.mts',
      'scripts/config.cts',
      'src/globals.d.ts',
      'scripts/runtime.d.mts',
      'scripts/runtime.d.cts',
    ]) {
      expect(isTypeScriptSourcePath(path), path).toBe(true);
    }
    for (const path of ['src/app.js', 'src/view.jsx', 'tsconfig.json', 'src/app.ts.map']) {
      expect(isTypeScriptSourcePath(path), path).toBe(false);
    }
  });

  it('fails a synthetic tracked source omitted from every tsc project file set', () => {
    const root = createTrackedFixture({
      'tsconfig.json': FIXTURE_TSCONFIG,
      'src/covered.ts': 'export const covered: string = "yes";\n',
      'orphan.mts': 'export const orphan: string = "missed";\n',
    });
    try {
      const result = runTypeScriptProjectCoverage(root, {
        projectPaths: ['tsconfig.json'],
        nonProjectConfigPaths: [],
        declarationExclusions: [],
      });

      expect(result.failures).toEqual([]);
      expect(result.missingPaths).toEqual(['orphan.mts']);
      expect(result.ok).toBe(false);
      expect(formatTypeScriptProjectCoverageFailures(result)).toContain(
        'Tracked or new unignored authored TypeScript is outside every tsc project file set: orphan.mts',
      );
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('accepts only validated generated and external declaration exclusions', () => {
    const root = createTrackedFixture({
      'tsconfig.json': FIXTURE_TSCONFIG,
      'src/covered.ts': 'export const covered: string = "yes";\n',
      'cloudflare/types/fixture.generated.d.ts':
        '/* eslint-disable */\n// Generated by Wrangler by running `wrangler types`\ninterface Env {}\n',
      'vendor/ambient.d.ts': "declare module 'vendor-package' { export const value: string; }\n",
    });
    const declarationExclusions = [
      {
        path: 'cloudflare/types/fixture.generated.d.ts',
        kind: 'generated',
        reason: 'Synthetic Wrangler output.',
      },
      {
        path: 'vendor/ambient.d.ts',
        kind: 'external',
        reason: 'Synthetic third-party package contract.',
      },
    ] as const satisfies readonly DeclarationExclusion[];

    try {
      const result = runTypeScriptProjectCoverage(root, {
        projectPaths: ['tsconfig.json'],
        nonProjectConfigPaths: [],
        declarationExclusions,
      });

      expect(result.ok).toBe(true);
      expect(result.failures).toEqual([]);
      expect(result.missingPaths).toEqual([]);
      expect(result.authoredTypeScriptPaths).toEqual(['src/covered.ts']);
      expect(result.excludedDeclarationPaths).toEqual([
        'cloudflare/types/fixture.generated.d.ts',
        'vendor/ambient.d.ts',
      ]);

      writeFileSync(
        join(root, 'cloudflare/types/fixture.generated.d.ts'),
        'interface HandWrittenContract {}\n',
      );
      const invalidResult = runTypeScriptProjectCoverage(root, {
        projectPaths: ['tsconfig.json'],
        nonProjectConfigPaths: [],
        declarationExclusions,
      });

      expect(invalidResult.ok).toBe(false);
      expect(invalidResult.failures).toContain(
        'Generated declaration exclusion lacks the Wrangler marker: cloudflare/types/fixture.generated.d.ts',
      );
      expect(invalidResult.missingPaths).toContain('cloudflare/types/fixture.generated.d.ts');
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });
});
