/**
 * Canonical eager-bootstrap contract.
 *
 * Runtime and Playwright checks derive their expected wiring count from this
 * list. A source-level contract test verifies that app.ts records these exact
 * steps in this exact order, so adding or removing an initializer cannot leave
 * a second magic counter stale.
 */
export const BOOTSTRAP_REQUIRED_STEPS = [
  'Platform',
  'OverlayObservers',
  'Toast',
  'EmailCopy',
  'Dialog',
  'Tabs',
  'I18n',
  'Account',
  'Account activity stats',
  'Account room identity',
  'Playback',
  'Playlist',
  'DecodeHandlers',
  'EffectsHandlers',
  'Protocol',
  'StandardQueueMutationAuthority',
  'PeerHandlers',
  'Sync',
  'SyncFlightRecorder',
  'Orchestrator',
  'SystemAudioCapture',
  'StandardOperatorFileUplink',
  'SyncWorker',
  'Transfer',
  'Preload',
  'Recovery',
  'RemoteShare',
  'YouTube',
  'YouTubeSync',
  'UiSounds',
  'Visualizer',
  'Chat',
  'PlaylistView',
  'PlayerControls',
  'GlobalFileDrop',
  'ClearableEditors',
  'Settings',
  'Connect',
  'CustomScrollbars',
  'Setup',
  'DemoMode',
  'AnnouncementPolling',
  'ProRoomBranding',
  'ServiceWorker',
  'KeyboardShortcuts',
  'WakeLock',
  'BackgroundResumeGuard',
  'PageLifecycle',
  'BackButtonGuard',
] as const;
