#!/usr/bin/env node

import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync } from 'node:fs';
import { dirname, isAbsolute, relative, resolve, sep } from 'node:path';
import { pathToFileURL } from 'node:url';
import ts from 'typescript';

const REPOSITORY_ROOT = resolve(import.meta.dirname, '..');
const TYPESCRIPT_SOURCE_RE = /\.(?:cts|mts|ts|tsx)$/iu;
const DECLARATION_RE = /\.d\.(?:cts|mts|ts)$/iu;
const GENERATED_DECLARATION_RE = /^cloudflare\/types\/[^/]+\.generated\.d\.ts$/u;
const WRANGLER_GENERATED_MARKER_RE = /Generated by Wrangler/u;
const EXTERNAL_DECLARATION_MARKER_RE =
  /(?:^|\n)\s*(?:declare\s+module\s+['"]|\/\/\/\s*<reference\s+types=)/u;

export interface DeclarationExclusion {
  readonly path: string;
  readonly kind: 'external' | 'generated';
  readonly reason: string;
}

export interface TypeScriptProjectCoverageOptions {
  readonly projectPaths?: readonly string[];
  readonly nonProjectConfigPaths?: readonly string[];
  readonly declarationExclusions?: readonly DeclarationExclusion[];
}

export interface TypeScriptProjectCoverageResult {
  readonly ok: boolean;
  readonly projectPaths: readonly string[];
  readonly candidateTypeScriptPaths: readonly string[];
  readonly authoredTypeScriptPaths: readonly string[];
  readonly coveredTypeScriptPaths: readonly string[];
  readonly excludedDeclarationPaths: readonly string[];
  readonly missingPaths: readonly string[];
  readonly failures: readonly string[];
}

export const DEFAULT_TSC_PROJECT_PATHS = Object.freeze([
  'tsconfig.json',
  'tsconfig.test.json',
  'src/workers/tsconfig.json',
  'tsconfig.cloudflare-leaves.json',
  'cloudflare/tsconfig.app.json',
  'cloudflare/tsconfig.pro-room.json',
  'cloudflare/tsconfig.signaling.json',
  'cloudflare/tsconfig.remote-share.json',
  'cloudflare/tsconfig.developer-api.json',
  'cloudflare/tsconfig.developer-api-facade.json',
  'tsconfig.browser-classic.json',
  'tsconfig.auxiliary-browser.json',
  'tsconfig.auxiliary-browser-remote.json',
  'tsconfig.service-worker.json',
  'tsconfig.ui-kit.json',
  'tsconfig.node-scripts.json',
  'tsconfig.workshop-landing.json',
  'tsconfig.tooling.json',
  'tsconfig.e2e.json',
] as const);

export const DEFAULT_NON_PROJECT_CONFIG_PATHS = Object.freeze([
  'cloudflare/tsconfig.worker.base.json',
] as const);

export const DEFAULT_DECLARATION_EXCLUSIONS = Object.freeze(
  [] as const satisfies readonly DeclarationExclusion[],
);

function normalizeRepositoryPath(path: string): string {
  return path.replaceAll('\\', '/').replace(/^\.\//u, '');
}

function pathKey(path: string): string {
  const normalized = normalizeRepositoryPath(path);
  return process.platform === 'win32' ? normalized.toLocaleLowerCase('en-US') : normalized;
}

function uniqueSorted(paths: readonly string[]): string[] {
  return [
    ...new Map(paths.map((path) => [pathKey(path), normalizeRepositoryPath(path)])).values(),
  ].sort((left, right) => left.localeCompare(right));
}

function repositoryPathForAbsolute(repositoryRoot: string, absolutePath: string): string | null {
  const candidate = relative(repositoryRoot, resolve(absolutePath));
  if (
    candidate === '' ||
    isAbsolute(candidate) ||
    candidate === '..' ||
    candidate.startsWith(`..${sep}`)
  ) {
    return null;
  }
  return normalizeRepositoryPath(candidate);
}

export function isTypeScriptSourcePath(path: string): boolean {
  return TYPESCRIPT_SOURCE_RE.test(normalizeRepositoryPath(path));
}

export function listCandidateRepositoryPaths(repositoryRoot: string): string[] {
  const output = execFileSync(
    'git',
    ['ls-files', '--cached', '--others', '--exclude-standard', '-z'],
    {
      cwd: repositoryRoot,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'pipe'],
    },
  );
  return output
    .split('\0')
    .filter((path) => path.length > 0)
    .map(normalizeRepositoryPath)
    .filter((path) => existsSync(resolve(repositoryRoot, path)))
    .sort((left, right) => left.localeCompare(right));
}

function isTypeScriptConfigPath(path: string): boolean {
  const name = normalizeRepositoryPath(path).split('/').at(-1) ?? '';
  return name === 'tsconfig.json' || /^tsconfig\..+\.json$/u.test(name);
}

function formatDiagnostic(configPath: string, diagnostic: ts.Diagnostic): string {
  return `${configPath}: TS${diagnostic.code}: ${ts.flattenDiagnosticMessageText(
    diagnostic.messageText,
    '\n',
  )}`;
}

function validateConfigInventory(
  repositoryRoot: string,
  trackedPaths: readonly string[],
  projectPaths: readonly string[],
  nonProjectConfigPaths: readonly string[],
): string[] {
  const failures: string[] = [];
  const trackedConfigPaths = uniqueSorted(trackedPaths.filter(isTypeScriptConfigPath));
  const trackedKeys = new Set(trackedConfigPaths.map(pathKey));
  const projectKeys = new Set<string>();
  const nonProjectKeys = new Set<string>();

  for (const rawPath of projectPaths) {
    const path = normalizeRepositoryPath(rawPath);
    const key = pathKey(path);
    if (projectKeys.has(key)) failures.push(`Duplicate tsc project entry: ${path}`);
    projectKeys.add(key);
    if (!trackedKeys.has(key))
      failures.push(`Configured tsc project is absent from repository candidates: ${path}`);
  }

  for (const rawPath of nonProjectConfigPaths) {
    const path = normalizeRepositoryPath(rawPath);
    const key = pathKey(path);
    if (nonProjectKeys.has(key)) failures.push(`Duplicate non-project tsconfig entry: ${path}`);
    nonProjectKeys.add(key);
    if (projectKeys.has(key))
      failures.push(`tsconfig is classified as both project and base: ${path}`);
    if (!trackedKeys.has(key)) {
      failures.push(
        `Configured non-project tsconfig is absent from repository candidates: ${path}`,
      );
      continue;
    }

    const configPath = resolve(repositoryRoot, path);
    const readResult = ts.readConfigFile(configPath, ts.sys.readFile);
    if (readResult.error) {
      failures.push(formatDiagnostic(path, readResult.error));
      continue;
    }
    const config = readResult.config as Record<string, unknown>;
    const inputKeys = ['files', 'include', 'references'].filter((name) =>
      Object.prototype.hasOwnProperty.call(config, name),
    );
    if (inputKeys.length > 0) {
      failures.push(
        `Non-project tsconfig now owns compiler inputs and must be classified as a tsc project: ${path} (${inputKeys.join(', ')})`,
      );
    }
  }

  for (const path of trackedConfigPaths) {
    const key = pathKey(path);
    if (!projectKeys.has(key) && !nonProjectKeys.has(key)) {
      failures.push(
        `Repository tsconfig is not classified as a project or input-free base: ${path}`,
      );
    }
  }

  return failures;
}

function collectProjectFileNames(
  repositoryRoot: string,
  projectPaths: readonly string[],
): { readonly paths: readonly string[]; readonly failures: readonly string[] } {
  const coveredPaths: string[] = [];
  const failures: string[] = [];

  for (const rawProjectPath of projectPaths) {
    const projectPath = normalizeRepositoryPath(rawProjectPath);
    const absoluteProjectPath = resolve(repositoryRoot, projectPath);
    if (!existsSync(absoluteProjectPath)) continue;

    const readResult = ts.readConfigFile(absoluteProjectPath, ts.sys.readFile);
    if (readResult.error) {
      failures.push(formatDiagnostic(projectPath, readResult.error));
      continue;
    }
    const parsed = ts.parseJsonConfigFileContent(
      readResult.config,
      ts.sys,
      dirname(absoluteProjectPath),
      undefined,
      absoluteProjectPath,
    );
    if (parsed.errors.length > 0) {
      failures.push(
        ...parsed.errors.map((diagnostic) => formatDiagnostic(projectPath, diagnostic)),
      );
      continue;
    }

    for (const absoluteFileName of parsed.fileNames) {
      const repositoryPath = repositoryPathForAbsolute(repositoryRoot, absoluteFileName);
      if (repositoryPath && isTypeScriptSourcePath(repositoryPath))
        coveredPaths.push(repositoryPath);
    }
  }

  return { paths: uniqueSorted(coveredPaths), failures };
}

function validateDeclarationExclusions(
  repositoryRoot: string,
  candidateTypeScriptPaths: readonly string[],
  exclusions: readonly DeclarationExclusion[],
): { readonly paths: readonly string[]; readonly failures: readonly string[] } {
  const failures: string[] = [];
  const trackedKeys = new Set(candidateTypeScriptPaths.map(pathKey));
  const seenKeys = new Set<string>();
  const validPaths: string[] = [];

  for (const exclusion of exclusions) {
    const path = normalizeRepositoryPath(exclusion.path);
    const key = pathKey(path);
    const entryFailures: string[] = [];

    if (
      isAbsolute(exclusion.path) ||
      /^[A-Za-z]:[\\/]/u.test(exclusion.path) ||
      path.startsWith('../')
    ) {
      entryFailures.push(`Declaration exclusion must be repository-relative: ${exclusion.path}`);
    }
    if (seenKeys.has(key)) entryFailures.push(`Duplicate declaration exclusion: ${path}`);
    seenKeys.add(key);
    if (!DECLARATION_RE.test(path)) {
      entryFailures.push(`Declaration exclusion must name a .d.ts file: ${path}`);
    }
    if (!exclusion.reason.trim())
      entryFailures.push(`Declaration exclusion needs a reason: ${path}`);
    if (!trackedKeys.has(key))
      entryFailures.push(`Declaration exclusion is absent from repository candidates: ${path}`);

    const absolutePath = resolve(repositoryRoot, path);
    if (!existsSync(absolutePath)) {
      entryFailures.push(`Declaration exclusion does not exist: ${path}`);
    } else {
      const source = readFileSync(absolutePath, 'utf8');
      if (exclusion.kind === 'generated') {
        if (!GENERATED_DECLARATION_RE.test(path)) {
          entryFailures.push(
            `Generated declaration exclusion must be a cloudflare/types/*.generated.d.ts file: ${path}`,
          );
        }
        if (!WRANGLER_GENERATED_MARKER_RE.test(source)) {
          entryFailures.push(`Generated declaration exclusion lacks the Wrangler marker: ${path}`);
        }
      } else if (!EXTERNAL_DECLARATION_MARKER_RE.test(source)) {
        entryFailures.push(
          `External declaration exclusion lacks an ambient module or type-reference marker: ${path}`,
        );
      }
    }

    if (entryFailures.length === 0) validPaths.push(path);
    failures.push(...entryFailures);
  }

  return { paths: uniqueSorted(validPaths), failures };
}

export function runTypeScriptProjectCoverage(
  repositoryRoot = REPOSITORY_ROOT,
  options: TypeScriptProjectCoverageOptions = {},
): TypeScriptProjectCoverageResult {
  const root = resolve(repositoryRoot);
  const projectPaths = uniqueSorted(options.projectPaths ?? DEFAULT_TSC_PROJECT_PATHS);
  const nonProjectConfigPaths = uniqueSorted(
    options.nonProjectConfigPaths ?? DEFAULT_NON_PROJECT_CONFIG_PATHS,
  );
  const declarationExclusions = options.declarationExclusions ?? DEFAULT_DECLARATION_EXCLUSIONS;
  const candidatePaths = listCandidateRepositoryPaths(root);
  const candidateTypeScriptPaths = uniqueSorted(candidatePaths.filter(isTypeScriptSourcePath));
  const configFailures = validateConfigInventory(
    root,
    candidatePaths,
    projectPaths,
    nonProjectConfigPaths,
  );
  const coverage = collectProjectFileNames(root, projectPaths);
  const exclusionValidation = validateDeclarationExclusions(
    root,
    candidateTypeScriptPaths,
    declarationExclusions,
  );
  const excludedKeys = new Set(exclusionValidation.paths.map(pathKey));
  const coveredKeys = new Set(coverage.paths.map(pathKey));
  const authoredTypeScriptPaths = candidateTypeScriptPaths.filter(
    (path) => !excludedKeys.has(pathKey(path)),
  );
  const missingPaths = authoredTypeScriptPaths.filter((path) => !coveredKeys.has(pathKey(path)));
  const failures = [...configFailures, ...coverage.failures, ...exclusionValidation.failures];

  return {
    ok: failures.length === 0 && missingPaths.length === 0,
    projectPaths,
    candidateTypeScriptPaths,
    authoredTypeScriptPaths,
    coveredTypeScriptPaths: coverage.paths,
    excludedDeclarationPaths: exclusionValidation.paths,
    missingPaths,
    failures,
  };
}

export function formatTypeScriptProjectCoverageFailures(
  result: TypeScriptProjectCoverageResult,
): string[] {
  return [
    ...result.failures,
    ...result.missingPaths.map(
      (path) =>
        `Tracked or new unignored authored TypeScript is outside every tsc project file set: ${path}`,
    ),
  ];
}

function main(): void {
  const result = runTypeScriptProjectCoverage();
  const failures = formatTypeScriptProjectCoverageFailures(result);
  if (failures.length > 0) {
    for (const failure of failures) process.stderr.write(`${failure}\n`);
    process.exitCode = 1;
    return;
  }

  process.stdout.write(
    `TypeScript project coverage includes ${result.authoredTypeScriptPaths.length} tracked/new unignored authored files across ${result.projectPaths.length} tsc projects; ${result.excludedDeclarationPaths.length} validated generated/external declarations are excluded.\n`,
  );
}

const invokedPath = process.argv[1] ? pathToFileURL(resolve(process.argv[1])).href : '';
if (invokedPath === import.meta.url) main();
