#!/usr/bin/env node

import { execFileSync } from 'node:child_process';
import { existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPOSITORY_ROOT = resolve(fileURLToPath(new URL('..', import.meta.url)));

export const DECLARATION_ALLOWLIST = Object.freeze({
  'browser/auxiliary-runtime/remote-modules.d.ts':
    'Pinned declarations for versioned browser CDN modules.',
  'browser/ui-kit/app/globals.d.ts': 'Narrow declarations for pinned React UMD globals.',
  'cloudflare/types/app.generated.d.ts': 'Generated by Wrangler from the App config.',
  'cloudflare/types/developer-api-facade.generated.d.ts':
    'Generated by Wrangler from the Developer API facade config.',
  'cloudflare/types/developer-api.generated.d.ts':
    'Generated by Wrangler from the Developer API config.',
  'cloudflare/types/pro-room.generated.d.ts': 'Generated by Wrangler from the PRO Room config.',
  'cloudflare/types/remote-share.generated.d.ts':
    'Generated by Wrangler from the Remote Share config.',
  'cloudflare/types/signaling.generated.d.ts': 'Generated by Wrangler from the Signaling config.',
  'scripts/types/subset-font.d.ts': 'Narrow declaration for an untyped third-party package.',
  'src/vite-env.d.ts': 'Vite client ambient declarations.',
} satisfies Readonly<Record<string, string>>);

export interface DeclarationOwnershipOptions {
  readonly declarations: readonly string[];
  readonly allowlist: Readonly<Record<string, string>>;
  readonly sourceExists: (path: string) => boolean;
}

export function nativeOwnerCandidates(declarationPath: string): string[] {
  if (declarationPath.endsWith('.d.mts')) {
    return [`${declarationPath.slice(0, -'.d.mts'.length)}.mts`];
  }
  if (declarationPath.endsWith('.d.cts')) {
    return [`${declarationPath.slice(0, -'.d.cts'.length)}.cts`];
  }
  if (declarationPath.endsWith('.d.ts')) {
    const stem = declarationPath.slice(0, -'.d.ts'.length);
    return [`${stem}.ts`, `${stem}.tsx`];
  }
  throw new Error(`${declarationPath}: unsupported declaration suffix`);
}

export function auditDeclarationOwnership(options: DeclarationOwnershipOptions): string[] {
  const declarations = [...new Set(options.declarations)].sort();
  const allowlisted = Object.keys(options.allowlist).sort();
  const failures: string[] = [];

  for (const declaration of declarations) {
    const nativeOwner = nativeOwnerCandidates(declaration).find(options.sourceExists);
    if (nativeOwner) {
      failures.push(`${declaration}: redundant declaration shadows native source ${nativeOwner}`);
      continue;
    }
    if (!(declaration in options.allowlist)) {
      failures.push(`${declaration}: declaration has no reviewed external/generated owner`);
    }
  }

  const declarationSet = new Set(declarations);
  for (const declaration of allowlisted) {
    if (!declarationSet.has(declaration)) {
      failures.push(`${declaration}: reviewed declaration is missing`);
    }
    if (!options.allowlist[declaration]?.trim()) {
      failures.push(`${declaration}: reviewed declaration reason is empty`);
    }
  }

  return failures;
}

export function repositoryDeclarationPaths(root = REPOSITORY_ROOT): string[] {
  return execFileSync(
    'git',
    [
      'ls-files',
      '-z',
      '--cached',
      '--others',
      '--exclude-standard',
      '--',
      ':(glob)**/*.d.ts',
      ':(glob)**/*.d.mts',
      ':(glob)**/*.d.cts',
    ],
    { cwd: root, encoding: 'utf8' },
  )
    .split('\0')
    .filter(Boolean)
    .filter((path) => existsSync(resolve(root, path)))
    .sort();
}

export function runDeclarationOwnershipCheck(root = REPOSITORY_ROOT): string[] {
  return auditDeclarationOwnership({
    declarations: repositoryDeclarationPaths(root),
    allowlist: DECLARATION_ALLOWLIST,
    sourceExists: (path) => existsSync(resolve(root, path)),
  });
}

function main(): void {
  const failures = runDeclarationOwnershipCheck();
  if (failures.length > 0) {
    for (const failure of failures) process.stderr.write(`${failure}\n`);
    process.exitCode = 1;
    return;
  }
  process.stdout.write(
    `[declaration-ownership] PASS: ${Object.keys(DECLARATION_ALLOWLIST).length} reviewed external/generated declarations.\n`,
  );
}

const invokedPath = process.argv[1] ? resolve(process.argv[1]) : '';
if (invokedPath === fileURLToPath(import.meta.url)) main();
